### ISSUE TITLE
Zdd doesn't compile

### ISSUE THREAD

**Issue by ishaihaviv** [AdrienChampion/zdd#1]
Compiling zdd v0.2.0
error[E0277]: the size for values of type `(dyn hashconsing::HashConsign<ZddTree<Label>> + 'static)` cannot be known at compilation time
   --> C:\Users\Roni\.cargo\registry\src\github.com-1ecc6299db9ec823\zdd-0.2.0\src\factory.rs:135:3
    |
135 |   consign: Mutex< HashConsign<ZddTree<Label>> >,
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: within `std::sync::Mutex<(dyn hashconsing::HashConsign<ZddTree<Label>> + 'static)>`, the trait `std::marker::Sized` is not implemented for `(dyn hashconsing::HashConsign<ZddTree<Label>> + 'static)`
    = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
    = note: required because it appears within the type `std::sync::Mutex<(dyn hashconsing::HashConsign<ZddTree<Label>> + 'static)>`
    = note: only the last field of a struct may have a dynamically sized type

error[E0038]: the trait `hashconsing::HashConsign` cannot be made into an object
   --> C:\Users\Roni\.cargo\registry\src\github.com-1ecc6299db9ec823\zdd-0.2.0\src\factory.rs:135:3
    |
135 |   consign: Mutex< HashConsign<ZddTree<Label>> >,
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `hashconsing::HashConsign` cannot be made into an object
    |
    = note: the trait cannot require that `Self : Sized`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0038, E0277.
For more information about an error, try `rustc --explain E0038`.
error: could not compile `zdd`.

**Comment by AdrienChampion** [comment]
Thank you for the report.

I had completely forgotten about this crate. It seems it's not used anymore, do you really need it? I can take a look soon-ish if you actually plan to use it. Otherwise I will just deprecate it...

**Comment by AdrienChampion** [comment]
@ishaihaviv

**Comment by AdrienChampion** [comment]
Well, despite your lack of answer I fixed it anyways. The [new version](https://crates.io/crates/zdd) should compile fine. It passes the tests, but as the warning I added to the readme and the docs says, I wrote it a long time ago so I can't make any promises in terms of correctness and efficiency.

You should be careful if you plan to use it seriously, and let me know so that I/we/someone can improve it.
